language: erlang

sudo: false
os: linux
otp_release:
  - 21.0.2
  - 20.3.8.2
  - 19.3.6.9
  - 18.3.4.9
  - 17.5.6.9
  - R16B03-1
  - R15B03-1

script: rebar3 eunit
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - ./rebar3 as prod compile
  # - ./rebar3 as check xref
  # - ./rebar3 as check dialyzer
  - ./rebar3 eunit

notifications:
  recipients:
    - hello@alind.io
